config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :questions

  resources :pools

  resources :subelements

  resources :groups

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/pool.rb
class Pool < ActiveRecord::Base
  has_many :questions
  has_many :subelements
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, only: [:show, :edit, :update, :destroy]

  # GET /pools
  # GET /pools.json
  def index
    @pools = Pool.all
  end

  # GET /pools/1
  # GET /pools/1.json
  def show
  end

  # GET /pools/new
  def new
    @pool = Pool.new
  end

  # GET /pools/1/edit
  def edit
  end

  # POST /pools
  # POST /pools.json
  def create
    @pool = Pool.new(pool_params)

    respond_to do |format|
      if @pool.save
        format.html { redirect_to @pool, notice: 'Pool was successfully created.' }
        format.json { render :show, status: :created, location: @pool }
      else
        format.html { render :new }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pools/1
  # PATCH/PUT /pools/1.json
  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to @pool, notice: 'Pool was successfully updated.' }
        format.json { render :show, status: :ok, location: @pool }
      else
        format.html { render :edit }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.json
  def destroy
    @pool.destroy
    respond_to do |format|
      format.html { redirect_to pools_url, notice: 'Pool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      @pool = Pool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pool_params
      params.require(:pool).permit(:number, :description, :slug, :source, :source_trail)
    end
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/_form.html.erb
<%= form_for @pool, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :number, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :slug, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :slug, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :source, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :source, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :source_trail, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :source_trail, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  pools_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/pools/edit.html.erb
<%- model_class = Pool -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Pool %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pools/index.html.erb
<%- model_class = Pool -%>
<div class="page-header">
  <h1><%=t '.title', :default => Pool %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:slug) %></th>
      <th><%= model_class.human_attribute_name(:source) %></th>
      <th><%= model_class.human_attribute_name(:source_trail) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pools.each do |pool| %>
      <tr>
        <td><%= pool.id %></td>
        <td><%= pool.number %></td>
        <td><%= pool.description %></td>
        <td><%= pool.slug %></td>
        <td><%= pool.source %></td>
        <td><%= pool.source_trail %></td>
        <td><%=l pool.created_at, format: :long %></td>
        <td>
          <%= link_to pool_path(pool), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to pool_path(pool), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pool_path,
            :class => 'btn btn-primary' %>

app/views/pools/new.html.erb
<%- model_class = Pool -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Pool %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pools/show.html.erb
<%- model_class = Pool -%>
<div class="page-header">
  <h1><%=t '.title', :default => Pool %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:number) %></dt>
      <dd><pre class="prettyprint"><%= @pool.number %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @pool.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:slug) %></dt>
      <dd><pre class="prettyprint"><%= @pool.slug %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:source) %></dt>
      <dd><pre class="prettyprint"><%= @pool.source %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:source_trail) %></dt>
      <dd><pre class="prettyprint"><%= @pool.source_trail %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pools_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_pool_path(@pool), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              pool_path(@pool),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>