config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :questions

  resources :pools

  resources :subelements

  resources :groups

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/subelement.rb
class Subelement < ActiveRecord::Base
  belongs_to :pool
  has_many :groups
end

app/controllers/subelements_controller.rb
class SubelementsController < ApplicationController
  before_action :set_subelement, only: [:show, :edit, :update, :destroy]

  # GET /subelements
  # GET /subelements.json
  def index
    @subelements = Subelement.all
  end

  # GET /subelements/1
  # GET /subelements/1.json
  def show
  end

  # GET /subelements/new
  def new
    @subelement = Subelement.new
  end

  # GET /subelements/1/edit
  def edit
  end

  # POST /subelements
  # POST /subelements.json
  def create
    @subelement = Subelement.new(subelement_params)

    respond_to do |format|
      if @subelement.save
        format.html { redirect_to @subelement, notice: 'Subelement was successfully created.' }
        format.json { render :show, status: :created, location: @subelement }
      else
        format.html { render :new }
        format.json { render json: @subelement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subelements/1
  # PATCH/PUT /subelements/1.json
  def update
    respond_to do |format|
      if @subelement.update(subelement_params)
        format.html { redirect_to @subelement, notice: 'Subelement was successfully updated.' }
        format.json { render :show, status: :ok, location: @subelement }
      else
        format.html { render :edit }
        format.json { render json: @subelement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subelements/1
  # DELETE /subelements/1.json
  def destroy
    @subelement.destroy
    respond_to do |format|
      format.html { redirect_to subelements_url, notice: 'Subelement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subelement
      @subelement = Subelement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subelement_params
      params.require(:subelement).permit(:number, :description, :slug, :pool_id)
    end
end

app/helpers/subelements_helper.rb
module SubelementsHelper
end

app/views/subelements/_form.html.erb
<%= form_for @subelement, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :number, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :slug, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :slug, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  subelements_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/subelements/edit.html.erb
<%- model_class = Subelement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Subelement %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subelements/index.html.erb
<%- model_class = Subelement -%>
<div class="page-header">
  <h1><%=t '.title', :default => Subelement %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:slug) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @subelements.each do |subelement| %>
      <tr>
        <td><%= subelement.id %></td>
        <td><%= subelement.number %></td>
        <td><%= subelement.description %></td>
        <td><%= subelement.slug %></td>
        <td><%=l subelement.created_at, format: :long %></td>
        <td>
          <%= link_to subelement_path(subelement), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to subelement_path(subelement), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_subelement_path,
            :class => 'btn btn-primary' %>

app/views/subelements/new.html.erb
<%- model_class = Subelement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Subelement %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subelements/show.html.erb
<%- model_class = Subelement -%>
<div class="page-header">
  <h1><%=t '.title', :default => Subelement %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:number) %></dt>
      <dd><pre class="prettyprint"><%= @subelement.number %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @subelement.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:slug) %></dt>
      <dd><pre class="prettyprint"><%= @subelement.slug %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              subelements_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_subelement_path(@subelement), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              subelement_path(@subelement),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>